// @ts-nocheck
"use client";

export default function PrivacyPolicy() {
  const s = {
    wrap: { maxWidth: 800, margin: "0 auto", padding: "40px 20px", fontFamily: "sans-serif", color: "#333", lineHeight: 1.6 },
    header: { display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "1px solid #eee", paddingBottom: 16, marginBottom: 24 },
    logo: { fontSize: 20, fontWeight: 900, color: "#ff4d00", textDecoration: "none" },
    title: { fontSize: 28, fontWeight: 900, margin: "0 0 8px", letterSpacing: -1 },
    sub: { fontSize: 13, color: "#888", margin: 0 },
    h2: { fontSize: 18, fontWeight: 700, margin: "24px 0 8px" }
  };

  return (
    <div style={s.wrap}>
      <header style={s.header}>
        <a href="/" style={s.logo}>EchoTakeout</a>
        <a href="/" style={{ color: "#555", textDecoration: "none", fontSize: 13, fontWeight: 600 }}>← Back to home</a>
      </header>

      <h1 style={s.title}>Privacy Policy</h1>
      <p style={s.sub}>Last updated: June 14, 2026</p>

      <p>EchoTakeout is a multi-tenant restaurant software-as-a-service platform operated by <strong>A SUGUNA ATHIVEERAPERUMAL</strong> ("we", "us", "our"). We are committed to protecting the privacy of both restaurant operators (our subscribers) and consumers (customers who place orders via restaurant menus powered by our software).</p>

      <h2 style={s.h2}>1. Data Collected from Restaurant Owners</h2>
      <p>To establish and support restaurant accounts, we collect and store:</p>
      <ul>
        <li>Account Information: Name, email address, password hashes, and contact phone numbers.</li>
        <li><strong>Restaurant Payment Configuration Data:</strong> Payment gateway configuration information, including API credentials provided by the restaurant for supported payment processors.</li>
        <li>Restaurant Configuration Data: Restaurant name, dynamic brand colors, tagline parameters, table setups, and custom operational constraints (e.g., queue limits).</li>
        <li>Menu Catalog Data: Item listings, descriptions, categories, prices, stock statuses, and item images.</li>
      </ul>

      <h2 style={s.h2}>2. Third-Party Payment Gateway Integration</h2>
      <p>When a merchant enables online payments, payment transactions may be processed through third-party payment service providers such as Razorpay using credentials configured by the restaurant. EchoTakeout does not store payment credentials beyond what is necessary to provide the payment integration and does not process payment funds directly.</p>

      <h2 style={s.h2}>3. Data Collected from Dining Customers</h2>
      <p>When a dining customer places an order at a subscriber's menu, we act strictly as a service provider (data processor) on behalf of the restaurant, collecting:</p>
      <ul>
        <li>Customer Name: Used by the restaurant to identify the order ticket.</li>
        <li>Mobile Number: Used by the restaurant to send order status alerts, KOT tokens, or clarify order details.</li>
        <li>Order Details: Selected items, table designations, customization instructions, and order totals.</li>
        <li>Payment References: Transaction IDs, order IDs, and verification parameters generated by third-party payment gateways (such as Razorpay). We do not collect or store card numbers, UPI PINs, or bank credentials.</li>
      </ul>

      <h2 style={s.h2}>4. Contact Information</h2>
      <p>For questions regarding data practices or this policy, please email support at <strong>echotakeout@gmail.com</strong>.</p>
    </div>
  );
}