// @ts-nocheck
"use client";

export default function PrivacyPolicy() {
  const s = {
    wrap: { maxWidth: 800, margin: "0 auto", padding: "40px 20px", fontFamily: "sans-serif", color: "#333", lineHeight: 1.6 },
    header: { display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "1px solid #eee", paddingBottom: 16, marginBottom: 24 },
    logo: { fontSize: 20, fontWeight: 900, color: "#ff4d00", textDecoration: "none" },
    title: { fontSize: 28, fontWeight: 900, margin: "0 0 8px", letterSpacing: -1 },
    sub: { fontSize: 13, color: "#888", margin: 0 },
    h2: { fontSize: 18, fontWeight: 700, margin: "24px 0 8px" }
  };

  return (
    <div style={s.wrap}>
      <header style={s.header}>
        <a href="/" style={s.logo}>EchoTakeout</a>
        <a href="/" style={{ color: "#555", textDecoration: "none", fontSize: 13, fontWeight: 600 }}>← Back to home</a>
      </header>

      <h1 style={s.title}>Privacy Policy</h1>
      <p style={s.sub}>Last updated: June 13, 2026</p>

      <p>EchoTakeout is a multi-tenant restaurant software-as-a-service platform operated by <strong>A SUGUNA ATHIVEERAPERUMAL</strong> ("we", "us", "our"). We are committed to protecting the privacy of both restaurant operators (our subscribers) and consumers (customers who place orders via restaurant menus powered by our software).</p>

      <h2 style={s.h2}>1. Scope of This Policy</h2>
      <p>This Privacy Policy describes how we collect, store, and process data for two distinct groups:</p>
      <ul>
        <li><strong>Restaurant Owners/Merchants:</strong> Independent business operators who subscribe to EchoTakeout.</li>
        <li><strong>Dining Customers:</strong> Individuals who place orders via QR code menus at our subscribers' physical locations.</li>
      </ul>

      <h2 style={s.h2}>2. Data Collected from Restaurant Owners</h2>
      <p>To establish and support restaurant accounts, we collect and store:</p>
      <ul>
        <li>Account Information: Name, email address, password hashes, and contact phone numbers.</li>
        <li>Restaurant Configuration Data: Restaurant name, dynamic brand colors, tagline parameters, table setups, and custom operational constraints (e.g., queue limits).</li>
        <li>Menu Catalog Data: Item listings, descriptions, categories, prices, stock statuses, and item images.</li>
      </ul>

      <h2 style={s.h2}>3. Data Collected from Dining Customers</h2>
      <p>When a dining customer places an order at a subscriber's menu, we act strictly as a service provider (data processor) on behalf of the restaurant, collecting:</p>
      <ul>
        <li>Customer Name: Used by the restaurant to identify the order ticket.</li>
        <li>Mobile Number: Used by the restaurant to send order status alerts, KOT tokens, or clarify order details.</li>
        <li>Order Details: Selected items, table designations, customization instructions, and order totals.</li>
        <li>Payment References: Transaction IDs, order IDs, and verification parameters generated by third-party payment gateways (such as Razorpay). We do not collect or store card numbers, UPI PINs, or bank credentials.</li>
      </ul>

      <h2 style={s.h2}>4. Third-Party Payment Gateway Sharing</h2>
      <p>EchoTakeout does not store or process payment funds. When a merchant enables online payments, checkout transactions are routed directly to the merchant's connected payment processor (Razorpay) using secure OAuth parameters. Data sharing with Razorpay is governed by Razorpay's Privacy Policy.</p>

      <h2 style={s.h2}>5. Data Security & Storage</h2>
      <p>Our platform database is hosted on secure cloud infrastructure provided by Supabase. We utilize cryptographic hashing to protect passwords and enforce secure network protocols (HTTPS/SSL) to protect all transactional data in transit.</p>

      <h2 style={s.h2}>6. Contact Information</h2>
      <p>For questions regarding data practices or this policy, please email support at <strong>echotakeout@gmail.com</strong>.</p>
    </div>
  );
}